"use client";

import { useEffect, useState } from "react";
import { revenueAPI } from "@/lib/api";
import { toast } from "sonner";
import { StatsCard } from "@/components/stats-card";
import { DollarSign, ShoppingCart, PieChart, UserPlus } from "lucide-react";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

export default function RevenuePage() {
  const [data, setData] = useState<any>(null);
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    async function loadRevenueData() {
      setIsLoading(true);
      try {
        const response = await revenueAPI.getRevenueData();
        if (response.success) {
          setData(response.data);
        } else {
          toast.error("Failed to load revenue data.");
        }
      } catch (error) {
        toast.error("An error occurred while fetching revenue data.");
      } finally {
        setIsLoading(false);
      }
    }
    loadRevenueData();
  }, []);

  if (isLoading) {
    return <p>Loading revenue data...</p>;
  }

  if (!data) {
    return <p>No revenue data available.</p>;
  }

  const { stats, subscriptions } = data;

  return (
    <div className="space-y-6">
      <div>
        <h3 className="text-lg font-medium">Revenue</h3>
        <p className="text-sm text-muted-foreground">
          Track revenue generated by the growth engine.
        </p>
      </div>

      <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
        <StatsCard
          title="Total Revenue"
          value={`$${stats.total_revenue.toFixed(2)}`}
          icon={DollarSign}
        />
        <StatsCard
          title="Total Subscriptions"
          value={stats.total_subscriptions}
          icon={ShoppingCart}
        />
        <StatsCard
          title="Creator Cut"
          value={`$${stats.total_creator_cut.toFixed(2)}`}
          icon={UserPlus}
        />
        <StatsCard
          title="Engine Cut"
          value={`$${stats.total_engine_cut.toFixed(2)}`}
          icon={PieChart}
        />
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Recent Subscriptions</CardTitle>
        </CardHeader>
        <CardContent>
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Subscription ID</TableHead>
                <TableHead>Revenue</TableHead>
                <TableHead>Your Cut</TableHead>
                <TableHead>Date</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {subscriptions.length > 0 ? (
                subscriptions.map((sub: any) => (
                  <TableRow key={sub.id}>
                    <TableCell className="font-medium">{sub.id}</TableCell>
                    <TableCell>${sub.revenue.toFixed(2)}</TableCell>
                    <TableCell className="text-green-600">${sub.creator_cut.toFixed(2)}</TableCell>
                    <TableCell>{new Date(sub.timestamp).toLocaleDateString()}</TableCell>
                  </TableRow>
                ))
              ) : (
                <TableRow>
                  <TableCell colSpan={4} className="h-24 text-center">
                    No subscriptions found.
                  </TableCell>
                </TableRow>
              )}
            </TableBody>
          </Table>
        </CardContent>
      </Card>
    </div>
  );
}
